### ISSUE TITLE
Push the change to changes array only if there is a change

### ISSUE THREAD

**Issue by vanand-conga** [VJAI/tiny#3]
In the `element.js` file we've a private method called `_pushChange`.

```js
 _pushChange(prop, value) {
    if (!this._changes.has(prop)) {
      this._changes.set(prop, { oldValue: this[prop], newValue: value });
      return;
    }

    const { oldValue, newValue } = this._changes.get(prop);
    /*if (oldValue === newValue) {
      this._changes.delete(prop);
      return;
    }*/

    this._changes.set(prop, { oldValue, newValue: value });
  }
```

What this method does if there is a change in the `input` property of a component it pushes to the `_changes` map. Finally the `onChanges` method is called with all the changes made.

We want to push it to the `_changes` map only if the old and new values are different. If we uncomment the commented code then the library fails during the initial render because at that time the values of the input props are either undefined or set to some default value so the both the old and new values are same. So we need to have some condition if the control is not yet initialized or rendered and then skip the check else check the old and new values and only push if they are different.

**Comment by vikramk0901** [comment]
Sure. Let me give it a shot.

**Comment by VJAI** [comment]
@vikramk0901 please review this PR https://github.com/VJAI/tiny/pull/8

**Comment by vikramk0901** [comment]
ok
